[package]
org = "wso2healthcare"
name = "FHIRAuthzService"
version = "0.9.0"
export = ["FHIRAuthzService"]
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Authorization", "Service"]

[build-options]
observabilityIncluded = true
