name: Publish Release

on:
    workflow_call:
      inputs:
        target-branch:
          description: 'Branch to target'
          type: string
          required: true
        service-name:
          description: 'Service name'
          type: string
          required: true
        working-dir:
          description: 'Working directory'
          type: string
          required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        ref: ${{ github.event.inputs.target-branch }}

     - name: Run ballerina build
       uses: ballerina-platform/ballerina-action@2201.8.4
       with:
        args:
          pack
       env:
          WORKING_DIR:  ${{ inputs.working-dir }}
          JAVA_HOME: /usr/lib/jvm/default-jvm   

     - name: Get tag from Ballerina.toml and create tag name
       working-directory: ${{ inputs.working-dir }}
       run: |
          VERSION_NO=$(grep -m 1 'version =' Ballerina.toml | cut -d '=' -f2 | sed 's/\"//g')
          echo "VERSION_NO='$VERSION_NO'" >> $GITHUB_ENV

          prefix=$(echo ${{ inputs.service-name }} | cut -d '-' -f 1-2)
          echo VERSION="${prefix}-v$(echo $VERSION_NO)" >> $GITHUB_ENV 

     - name: Create Release
       id: create_release
       run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "'"$VERSION"'",
              "target_commitish": "${{ github.event.inputs.target-branch }}",
              "name": "'"$VERSION"'",
              "body": "Releases",
              "draft": false,
              "prerelease": false,
              "generate_release_notes": false
            }'
